# Generated by Django 5.0.3 on 2024-04-09 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='post',
            name='creation_date',
            field=models.DateField(default=datetime.date(2024, 4, 9)),
        ),
        migrations.AddField(
            model_name='post',
            name='creation_time',
            field=models.TimeField(default=datetime.time(13, 24, 42, 36838)),
        ),
    ]
