# Generated by Django 5.0.3 on 2024-03-21 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_auctionlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='startingbid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bids',
            name='BidAmount',
            field=models.IntegerField(),
        ),
    ]
