# Generated by Django 5.0.3 on 2024-03-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_user_alter_auctionlisting_startingbid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='onwatchlist',
            field=models.BooleanField(default=False),
        ),
    ]
