# Generated by Django 5.0.3 on 2024-03-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_bid_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bids',
        ),
    ]
