# Generated by Django 5.0.3 on 2024-03-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_delete_bids'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bid',
            table='auctions_bid',
        ),
    ]
