# Generated by Django 5.0.3 on 2024-04-10 20:02

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_user_followers_alter_post_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_time',
            field=models.TimeField(default=datetime.time(20, 2, 20, 46964)),
        ),
    ]
