# Generated by Django 5.0.3 on 2024-04-17 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_post_creation_date_alter_post_creation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.URLField(default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateField(default=datetime.date(2024, 4, 17)),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_time',
            field=models.TimeField(default=datetime.time(15, 12, 55, 960486)),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
